version: '3.8'
services:

  site:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    restart: unless-stopped
    volumes:
      - '.:/app'
      - './node_modules:/app/node_modules:cached'
    ports:
      - "3002:3000"

